app/events/urls.py
from django.contrib import admin
from django.urls import include, path
from backend.views import CustomAdminPasswordChangeView

urlpatterns = [
    #path('admin/backend/', include('backend.urls')),
    path(
        'admin/backend/user/<int:pk>/password/',
        CustomAdminPasswordChangeView.as_view(),
    ),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('ecal/', include(('events_calendar.urls'), namespace='ecal')),
    path('profile/', include(('profile_page.urls'), namespace='profile')),

]

app/events_calendar/urls.py
from django.urls import path
from . import views

# for class based views the login_required decorator can also be implemented here
# e.g. path('calendar/', login_required(views.CalendarView.as_view()), name='calendar'),
# but the ussage of the mixin within views.py seems more convenient
app_name = 'events_calendar'
urlpatterns = [
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.event, name='event_new'),
    path('event/edit/(?<event_id>\d+)/', views.event, name='event_edit'),
    path('past_event/edit/(?<past_event_id>\d+)/', views.past_event, name='past_event_edit'),
    path('task/edit/(?<task_id>\d+)/', views.task, name='task_edit'),
    path('task/new/', views.task, name='task_new'),
    path('task/new/<int:event_id>', views.task, name='event_task_new'),
]

app/polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('harry/', views.harry, name='harry'),
]

app/profile_page/urls.py
from django.urls import path
from . import views

# for class based views the login_required decorator can also be implemented here
# e.g. path('calendar/', login_required(views.CalendarView.as_view()), name='calendar'),
# but the ussage of the mixin within views.py seems more convenient
app_name = 'profile_page'
urlpatterns = [
    path('hub/', views.ProfileHub.as_view(), name='hub'),
    path('account/<int:pk>/', views.Account.as_view(), name='account'),
    path('adress/edit/<int:pk>/', views.UpdateAdress.as_view(), name='adress_edit'),
    path('adress/create/', views.CreateAdress.as_view(), name='adress_create'),
]

app/templates/base.html
<!-- events/templates/base.html -->

{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap -->
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  {% block stylesheet %}
  {% endblock %}

  {% block bootstrap5_extra_head %}
  {{ block.super }}
  <link href="{% static 'dark_mode_switch/dark-mode-switch.css' %}" rel="stylesheet" type="text/css">
  {% endblock %}

  {% block bootstrap5_extra_script %}
  {{ block.super }}
  <script src="{% static 'dark_mode_switch/dark-mode-switch.js' %}"></script>
  {% endblock %}

  <title>{% block title %} Veranstaltungen {% endblock %}</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg fixed-top navbar-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'ecal:calendar' %}"> UT Connewitz Veranstaltungen </a>

      <button class="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'ecal:calendar' %}"> &#128197; Kalender </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile:hub' %}"> &#10003; Dienste und Einstellungen </a>
          </li>
          {% if request.user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}"> &#9096; Administration </a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}"> &#8618; Abmelden </a>
          </li>
          {% include 'dark_mode_switch/dark_mode_switch.html' %}
        </ul>
      </div>

    </div>
  </nav>


  {% block content %}
  {% endblock %}

  {% block script %}
  {% endblock %}

<footer class="text-center fixed-bottom">
  <div class="container p-1">
    <span>
      <a href="https://github.com/ut-connewitz/event-management"> public source code repository </a>
    </span>
  </div>
</footer>

</body>
</html>