app/events/urls.py
from django.contrib import admin
from django.urls import include, path
from backend.views import CustomAdminPasswordChangeView

urlpatterns = [
    #path('admin/backend/', include('backend.urls')),
    path(
        'admin/backend/user/<int:pk>/password/',
        CustomAdminPasswordChangeView.as_view(),
    ),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('ecal/', include(('events_calendar.urls'), namespace='ecal')),
    path('profile/', include(('profile_page.urls'), namespace='profile')),

]

app/events_calendar/urls.py
from django.urls import path
from . import views

# for class based views the login_required decorator can also be implemented here
# e.g. path('calendar/', login_required(views.CalendarView.as_view()), name='calendar'),
# but the ussage of the mixin within views.py seems more convenient
app_name = 'events_calendar'
urlpatterns = [
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.event, name='event_new'),
    path('event/edit/(?<event_id>\d+)/', views.event, name='event_edit'),
    path('past_event/edit/(?<past_event_id>\d+)/', views.past_event, name='past_event_edit'),
    path('task/edit/(?<task_id>\d+)/', views.task, name='task_edit'),
    path('task/new/', views.task, name='task_new'),
    path('task/new/<int:event_id>', views.task, name='event_task_new'),
]

app/polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('harry/', views.harry, name='harry'),
]

app/events_calendar/forms.py
from django.forms import ModelForm, DateInput, TimeInput, BooleanField, HiddenInput, DateField
from backend.models.event import Event, PastEvent
from backend.models.task import Task, Volunteering
from datetime import datetime

import logging

class EventForm(ModelForm):
    class Meta:
        model = Event
        widgets = {
            'date': DateInput(
                format=('%d.%m.%Y'),
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Datum wählen',
                    #'type': 'date',
                    # chosing the 'type': 'date' option enables the actual date-picking widget
                    # but defaults the input value to the current date and makes saving dates impossible
                    # due to a format error
                    }),
            'start_time': TimeInput(
                format=('%H:%M'),
                attrs={
                    'type': 'time-local',
                    'class': 'form-control'}),
            'admission_time': TimeInput(
                format=('%H:%M'),
                attrs={
                'type': 'time-local',
                'class': 'form-control'}),
            'duration': TimeInput(
                format=('%H:%M'),
                attrs={
                    'class': 'form-control'}),
        }
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['start_time'].input_formats = ('%H:%M',)
        self.fields['admission_time'].input_formats = ('%H:%M',)
        self.fields['duration'].input_formats = ('%H:%M',)
        #self.fields['duration'].help_text = 'Eingabeformat der Veranstaltungsdauer: HH:MM'
        self.fields['date'].input_formats = ('%d.%m.%Y',)
        #logger = logging.getLogger(__name__) #debug
        #logger.error(str(self.instance.date)) #debug
        #logger.error(str(self.instance.date.strftime('%d.%m.%Y')))
        #self.fields['date'].initial = self.instance.date.strftime('%d.%m.%Y')
        #self.fields['date'].initial = self.instance.date

class PastEventForm(ModelForm):
    class Meta:
        model = PastEvent
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PastEventForm, self).__init__(*args, **kwargs)
        self.fields['start_time'].input_formats = ('%H:%M',)
        self.fields['date'].input_formats = ('%d.%m.%Y',)
        #logger = logging.getLogger(__name__) #debug
        #logger.error(str(self.instance.date)) #debug
        #logger.error(str(self.instance.date.strftime('%d.%m.%Y')))
        #self.fields['date'].initial = self.instance.date.strftime('%d.%m.%Y')

class TaskForm(ModelForm):
    # this hidden fields purpose is determine which form is submitted in the post request
    # it is needed because there are two different forms (TaskForm and VolunteeringForm) on one page
    edit_task = BooleanField(widget=HiddenInput, initial=True)

    class Meta:
        model = Task
        widgets = {
            'start_time': TimeInput(
                format=('%H:%M'),
                attrs={
                    'type': 'time-local',
                    'class': 'form-control'}),
            'finish_time': TimeInput(
                format=('%H:%M'),
                attrs={
                    'type': 'time-local',
                    'class': 'form-control'}),
        }
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        self.fields['start_time'].input_formats = ('%H:%M',)
        self.fields['finish_time'].input_formats = ('%H:%M',)

        #if request.user.is_staff == False:
        #    self.fields['event_day', 'task_type', 'team_restriction', 'urgency', 'state', 'start_time', 'finish_time', 'comment'].disabled = True


class VolunteeringForm(ModelForm):
    edit_volunteering = BooleanField(widget=HiddenInput, initial=True)

    class Meta:
        model = Volunteering
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(VolunteeringForm, self).__init__(*args, **kwargs)

app/events_calendar/views.py
from datetime import datetime, timedelta, date
import calendar
import logging

from django.conf import settings
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.timezone import now
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import HiddenInput


from backend.models.event import Event, PastEvent
from backend.models.task import Task, Volunteering, ConfirmationType, State
from .utils import Calendar
from .forms import EventForm, PastEventForm, TaskForm, VolunteeringForm


class CalendarView(LoginRequiredMixin, generic.ListView):
    model = Event
    template_name = 'events_calendar/calendar.html'

    def get_context_data(self, **kwargs,):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        today = get_date(self.request.GET.get('month', None))

        # Instantiate our calendar class with today's year and date
        calendar = Calendar(self.request.user, today.year, today.month)

        # Call the formatmonth method, which returns our calendar as a table
        html_calendar = calendar.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_calendar)

        context['prev_month'] = prev_month(today)
        context['next_month'] = next_month(today)
        return context

def get_date(requested_day):
    if requested_day:
        year, month = (int(x) for x in requested_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(today):
    first = today.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(today):
    days_in_month = calendar.monthrange(today.year, today.month)[1]
    last = today.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

@login_required
def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
        initial_date = instance.date.strftime('%d.%m.%Y')
    else:
        instance = Event()
        event_id = instance.event_id
        initial_date = now().date().strftime('%d.%m.%Y')
        #logger = logging.getLogger(__name__) #debug
        #logger.error('new instance id: '+str(event_day_id)) #debug

    #logger = logging.getLogger(__name__) #debug
    #logger.error(str(instance.date)) #debug
    #logger.error(str(instance.date.strftime('%d.%m.%Y')))

    form = EventForm(
        request.POST or None,
        instance=instance,
        initial={
            'date': initial_date
        }
    )
    if not request.user.is_staff:
        form.fields['series'].disabled = True
        form.fields['subtitle'].disabled = True
        form.fields['date'].disabled = True
        form.fields['start_time'].disabled = True
        form.fields['duration'].disabled = True
        form.fields['admission_time'].disabled = True
        form.fields['location'].disabled = True

    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('ecal:calendar'))

    context = {
        'event_id' : event_id,
        'form': form,
    }
    return render(request, 'events_calendar/event.html', context=context)

@login_required
def past_event(request, past_event_id=None):

    instance = get_object_or_404(PastEvent, pk=past_event_id)

    form = PastEventForm(
        request.POST or None,
        instance=instance,
        initial={
            'date': instance.date.strftime('%d.%m.%Y')
        }
    )

    form.fields['series'].disabled = True
    form.fields['subtitle'].disabled = True
    form.fields['date'].disabled = True
    form.fields['start_time'].disabled = True
    form.fields['duration'].disabled = True
    form.fields['location'].disabled = True

    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('ecal:calendar'))

    context = {
        'past_event_id' : past_event_id,
        'form': form,
    }
    return render(request, 'events_calendar/past_event.html', context=context)

@login_required
def task(request, task_id=None, volunteering_id=None, event_id=None):
    task_instance = Task()
    if task_id:
        task_instance = get_object_or_404(Task, pk=task_id)
    else:
        task_instance = Task()

    task_id = task_instance.task_id

    volunteering_instance = Volunteering()
    is_new_volunteering = False
    try:
        volunteering_instance = Volunteering.objects.get(
            task = task_instance,
        )
    except Volunteering.DoesNotExist:
        volunteering_instance = Volunteering(
            task = task_instance,
            user = request.user,
        )
        is_new_volunteering = True


    if event_id:
        event = Event.objects.get(event_id=event_id)
        task_form = TaskForm(request.POST or None, instance=task_instance, initial={'event': event})
    else:
        task_form = TaskForm(request.POST or None, instance=task_instance)

    volunteering_form = VolunteeringForm(
        request.POST or None,
        instance=volunteering_instance,
        initial={
            'confirmation_type': ConfirmationType.YES,
            'user': request.user,
        })
    if is_new_volunteering:
        volunteering_form.fields['confirmation_type'].disabled = True

    if not request.user.is_staff:
        task_form.fields['event'].disabled = True
        task_form.fields['task_type'].disabled = True
        task_form.fields['team_restriction'].disabled = True
        task_form.fields['urgency'].disabled = True
        #task_form.fields['state'].disabled = True # set to 'editable=False' in model, so it doesnt exist as field here
        task_form.fields['start_time'].disabled = True
        task_form.fields['finish_time'].disabled = True
        task_form.fields['comment'].disabled = True

        volunteering_form.fields['user'].widget = HiddenInput()
        volunteering_form.fields['task'].widget = HiddenInput()
        #volunteering_form.fields['user'].widget.attrs['readonly'] = True
        #volunteering_form.fields['task'].widget.attrs['readonly'] = True
        if request.user != volunteering_instance.user:
            volunteering_form.fields['confirmation_type'].widget = HiddenInput()
            volunteering_form.fields['comment'].widget = HiddenInput()
            #volunteering_form.fields['confirmation_type'].widget.attrs['readonly'] = True
            #volunteering_form.fields['confirmation_type'].disabled

        #    volunteering_form.fields['user'].widget = HiddenInput()

        # experimental integration of ConfirmationType.MAYBE
        # idea: show volunteering, but do not show, who cofirmed with maybe
        # make it possible, to confirm with ConfirmationType.YES only and delete previous MAYBE confirmation
        # problem: when save button is clicked without changing anything an error is thrown, that makes ALL form fields freely accesible
        # so the user could select anyone for any task
        #elif request.user != volunteering_instance.user and volunteering_instance.confirmation_type == ConfirmationType.MAYBE:
        #    volunteering_form.fields['user'].widget = HiddenInput()

        # this loop did not work: File "/app/events_calendar/views.py", line 90, in task 'field.disabled = True'
        #for field in form.fields:
        #    field.disabled = True

    if request.method == 'POST':
        if 'edit_task' in request.POST:
            if task_form.is_valid():
                task_form.save()
                return HttpResponseRedirect(reverse('ecal:calendar'))

        if 'edit_volunteering' in request.POST and (request.user == volunteering_instance.user or request.user.is_staff):
            if volunteering_form.is_valid() and request.POST.get('volunteering_button')=="volunteering":
                confirmation_type = volunteering_form.cleaned_data["confirmation_type"]
                volunteering_form.save()
                # volunteering state change logic located at model file (backend/models/task/volunteering.py)
                # in order to make it effective regardless of the source of the change

                return HttpResponseRedirect(reverse('ecal:calendar'))

    # note: context variables are accessable within template code blocks
    # e.g. {% if request.user == volunteering_instance.user %}
    context = {
        'task_form': task_form,
        'volunteering_form': volunteering_form,
        'volunteering_instance': volunteering_instance,
    }
    return render(request, 'events_calendar/task.html', context=context)

app/events_calendar/templates/events_calendar/base.html
<!-- events_calendar/templates/events_calendar/base.html -->

{% extends 'base.html' %}
{% load static %}


<head>
  <!-- Required meta tags -->
  {% block stylesheet %} <link rel="stylesheet" type="text/css" href="{% static 'events_calendar/css/calendar.css' %}"> {% endblock %}

</head>

app/events_calendar/templates/events_calendar/calendar.html
<!-- events_calendar/templates/events_calendar/calendar.html -->

{% extends 'events_calendar/base.html' %}

{% block title %}
Kalender
{% endblock %}

{% block content %}

<div class="clearfix">
	<a class="btn btn-secondary left" href="{% url 'ecal:calendar' %}?{{ prev_month }}"> Vorheriger Monat </a>
	<a class="btn btn-secondary right" href="{% url 'ecal:calendar' %}?{{ next_month }}"> Nächster Monat </a>
  {% if request.user.is_staff %}
  <div class="d-grip gap-2 col-6 mx-auto">
    <a class="btn btn-secondary" href="{% url 'ecal:event_new' %}"> Veranstaltung hinzufügen </a>
    <a class="btn btn-secondary" href="{% url 'ecal:task_new' %}"> Aufgabe hinzufügen </a>
  </div>
  {% endif %}
</div>

<table border="0" cellpadding="0" cellspacing="1%" class="calendar">
  {{ calendar }}
</table>
{% endblock %}

app/events_calendar/templates/events_calendar/event.html
{% extends 'events_calendar/base.html' %}

{% block title %}
Veranstaltung
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-secondary left" href="{% url 'ecal:calendar' %}"> Kalender </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    {% if request.user.is_staff %}
    <tr><td colspan="2"><button type="submit" class="btn btn-secondary right"> Speichern </button></td></tr>
    {% endif %}
  </table>
</form>

<div class="clearfix">
  {% if request.user.is_staff %}
    {% if event_id is None %}
    <a class="btn btn-secondary right" href="{% url 'ecal:task_new' %}"> Aufgabe hinzufügen </a>
    {% else %}
    <a class="btn btn-secondary right" href="{% url 'ecal:event_task_new' event_id=event_id %}"> Aufgabe hinzufügen </a>
    {% endif %}
  {% endif %}
</div>
{% endblock %}

app/events_calendar/templates/events_calendar/event_day.html
{% extends 'events_calendar/base.html' %}

{% block title %}
Veranstaltungstag
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'ecal:calendar' %}"> Kalender </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    {% if request.user.is_staff %}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Speichern </button></td></tr>
    {% endif %}
  </table>
</form>

<div class="clearfix">
  {% if request.user.is_staff %}
    {% if event_day_id is None %}
    <a class="btn btn-info right" href="{% url 'ecal:task_new' %}"> Aufgabe hinzufügen </a>
    {% else %}
    <a class="btn btn-info right" href="{% url 'ecal:event_task_new' event_day_id=event_day_id %}"> Aufgabe hinzufügen </a>
    {% endif %}
  {% endif %}
</div>
{% endblock %}

app/events_calendar/templates/events_calendar/past_event.html
{% extends 'events_calendar/base.html' %}

{% block title %}
Vergangene Veranstaltung
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-secondary left" href="{% url 'ecal:calendar' %}"> Kalender </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    {% if request.user.is_staff %}
    <tr><td colspan="2"><button type="submit" class="btn btn-secondary right"> Speichern </button></td></tr>
    {% endif %}
  </table>
</form>
{% endblock %}

app/events_calendar/templates/events_calendar/task.html
{% extends 'events_calendar/base.html' %}

{% block title %}
Aufgabe
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-secondary left" href="{% url 'ecal:calendar' %}"> Kalender </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  <table class="form form-table">
    <h2 style="text-align:center;"> Aufgabe </h2>
    {{ task_form }}
    {% csrf_token %}
    {% if request.user.is_staff %}
    <tr><td colspan="2"><button type="submit" class="btn btn-secondary right" name="task_button" value="task"> Speichern </button></td></tr>
    {% endif %}
  </table>
</form>
<hr>

<form method="post">
  <table class="form form-table">
    {% if request.user == volunteering_instance.user %}
    <h2 style="text-align:center;"> Übernehmen? </h2>
    {% endif %}
    {{ volunteering_form}}
    {% csrf_token %}
    {% if request.user == volunteering_instance.user or request.user.is_staff %}
    <tr><td colspan="2"><button type="submit" class="btn btn-secondary right" name="volunteering_button" value="volunteering"> Speichern </button></td></tr>
    {% endif %}
    {% if request.user != volunteering_instance.user %}
    <h3 style="text-align:center;"> – Bereits übernommen – </h3>
    {% endif %}
  </table>
</form>
<hr>

{% endblock %}